### ISSUE TITLE
Failed to load data when the tain dataset is 114G?

### ISSUE THREAD

**Issue by xiaochunsong92** [swift-n-brutal/illuminant_estimation#2]
When I try to replace gs568 with our own dataset, it takes very long time to zmq_poll the dataset. it will load all the train data once?

**Comment by swift-n-brutal** [comment]
Yes. The training data are stored in memory for efficiency. Specifically, all the images are stored in the list gs568_dataset.py:GS568Dataset._data. I will add a patch later to support dynamic loading. If the format of your data is different from that of gs568, you can modify GS568Dataset._get() to read you own data.

**Comment by xiaochunsong92** [comment]
Thanks for your reply, Yes, I find if self.__cache is TRUE， It will load all dataset, and _get() to get the data and illums. The format is the same of gs568, but only number increasing.  I'll try to do some dynamic loading tests, but i'm not familiar with ZMQ. So anticipate your later update :)

**Comment by swift-n-brutal** [comment]
The option for cache=False is implemented. However, the training speed becomes extremely slow, because we need to load the whole image (which has about 3M pixels) before cropping a small patch (44x44). I tried adding 30 (--nproc 30) processes to load data, but the speed is still slower than that of the cached version. If your image size is comparable to the patch size, this may not be a problem. Otherwise, you need to cut your image into small pieces or consider using other sampling strategies.

In case you want to use other magics, you can derive your own dataset from dataloaders.Dataset without knowing ZMQ. GS568Dataset and CifarDataset are two examples.
